# Generated by Django 2.2.12 on 2020-05-02 13:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiler_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBPediaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DBPediaPersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persondata', jsonfield.fields.JSONField()),
            ],
        ),
    ]
